# GLEW_FOUND
# GLEW_INCLUDE_DIRS
# GLEW_LIBRARIES

find_path(GLEW_INCLUDE_DIR GL/glew.h)

find_library(GLEW_LIBRARY
    NAMES glew32 glew glew32s 
    PATH_SUFFIXES lib64)

set(GLEW_INCLUDE_DIRS ${GLEW_INCLUDE_DIR})
set(GLEW_LIBRARIES ${GLEW_LIBRARY})

find_package_handle_standard_args(GLEW DEFAULT_MSG GLEW_LIBRARY GLEW_INCLUDE_DIR)
mark_as_advanced(GLEW_FOUND GLEW_INCLUDE_DIR GLEW_LIBRARY)